PERMISSIONS_MAP = {
    "RECEPTIONIST": [
        ("can_create_client", "Pode cadastrar Cliente"),
        ("can_view_client_info", "Pode ver informações de Cliente"),
        ("view_system_users", "Pode ver as próprias informações"),
        ("can_view_client_list", "Pode ver lista de Cliente"),
        ("can_create_appointment", "Pode criar agendamento"),
        ("can_view_appointment_list", "Pode ver lista de agendamento"),
        ("can_view_appointment_info", "Pode ver detalhes de agendamento"),
        ("can_edit_appointment", "Pode editar agendamento"),
        ("can_view_therapist_info", "Pode ver informações de terapeuta"),
        ("can_view_therapist_list", "Pode ver lista de terapeuta"),
    ],
    "THERAPIST": [
        ("can_create_appointment", "Pode criar agendamento"),
        ("can_view_appointment_list", "Pode ver lista de agendamento"),
        ("can_view_appointment_info", "Pode ver detalhes de agendamento"),
        ("can_edit_appointment", "Pode editar agendamento"),
        ("can_remove_appointment", "Pode remover agendamento"),
        ("can_view_therapist_info", "Pode ver informações de terapeuta"),
        ("can_view_therapist_list", "Pode ver lista de terapeuta"),
        ("modify_therapist_information", "Pode editar informações de terapeuta"),
    ],
    "MANAGER": [
        ("can_create_client", "Pode cadastrar Cliente"),
        ("can_view_client_info", "Pode ver informações de Cliente"),
        ("can_view_client_list", "Pode ver lista de Cliente"),
        ("modify_patient_information", "Pode editar informações de Cliente"),
        ("can_create_therapist", "Pode cadastrar terapeuta"),
        ("can_view_therapist_info", "Pode ver informações de terapeuta"),
        ("can_view_therapist_list", "Pode ver lista de terapeuta"),
        ("modify_therapist_information", "Pode editar informações de terapeuta"),
        ("manage_system_users", "Pode gerenciar usuários do sistema"),
    ],
    "GENERAL_MANAGER": [
        ("can_create_client", "Pode cadastrar Cliente"),
        ("can_view_client_info", "Pode ver informações de Cliente"),
        ("can_view_client_list", "Pode ver lista de Cliente"),
        ("modify_patient_information", "Pode editar informações de Cliente"),
        ("can_create_appointment", "Pode criar agendamento"),
        ("can_view_appointment_list", "Pode ver lista de agendamento"),
        ("can_view_appointment_info", "Pode ver detalhes de agendamento"),
        ("can_edit_appointment", "Pode editar agendamento"),
        ("can_remove_appointment", "Pode remover agendamento"),
        ("can_create_therapist", "Pode cadastrar terapeuta"),
        ("can_view_therapist_info", "Pode ver informações de terapeuta"),
        ("can_view_therapist_list", "Pode ver lista de terapeuta"),
        ("modify_therapist_information", "Pode editar informações de terapeuta"),
        ("manage_system_users", "Pode gerenciar usuários do sistema"),
    ],
    "ADMINISTRATOR": [
        ("can_create_client", "Pode cadastrar Cliente"),
        ("can_view_client_info", "Pode ver informações de Cliente"),
        ("can_view_client_list", "Pode ver lista de Cliente"),
        ("modify_patient_information", "Pode editar informações de Cliente"),
        ("can_create_appointment", "Pode criar agendamento"),
        ("can_view_appointment_list", "Pode ver lista de agendamento"),
        ("can_view_appointment_info", "Pode ver detalhes de agendamento"),
        ("can_edit_appointment", "Pode editar agendamento"),
        ("can_remove_appointment", "Pode remover agendamento"),
        ("can_create_therapist", "Pode cadastrar terapeuta"),
        ("can_view_therapist_info", "Pode ver informações de terapeuta"),
        ("can_view_therapist_list", "Pode ver lista de terapeuta"),
        ("modify_therapist_information", "Pode editar informações de terapeuta"),
        ("manage_system_users", "Pode gerenciar usuários do sistema"),
    ],
    "SUPER_USER": [
        ("can_create_client", "Pode cadastrar Cliente"),
        ("can_view_client_info", "Pode ver informações de Cliente"),
        ("can_view_client_list", "Pode ver lista de Cliente"),
        ("modify_patient_information", "Pode editar informações de Cliente"),
        ("can_create_appointment", "Pode criar agendamento"),
        ("can_view_appointment_list", "Pode ver lista de agendamento"),
        ("can_view_appointment_info", "Pode ver detalhes de agendamento"),
        ("can_edit_appointment", "Pode editar agendamento"),
        ("can_remove_appointment", "Pode remover agendamento"),
        ("can_create_therapist", "Pode cadastrar terapeuta"),
        ("can_view_therapist_info", "Pode ver informações de terapeuta"),
        ("can_view_therapist_list", "Pode ver lista de terapeuta"),
        ("modify_therapist_information", "Pode editar informações de terapeuta"),
        ("manage_system_users", "Pode gerenciar usuários do sistema"),
    ],
}
