# Generated by Django 4.2.7 on 2023-11-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_council', models.CharField(choices=[('CRAD-DF', 'Conselho Regional de Acupuntura do Distrito Federal (CRAD-DF)'), ('COBRA', 'Conselho de Osteopatia de Brasília (COBRA)'), ('CHM-DF', 'Conselho de Hipnose Médica do Distrito Federal (CHM-DF)'), ('COMIBRA', 'Conselho de Medicina Integrativa de Brasília (COMIBRA)'), ('CRTCD-DF', 'Conselho Regional de Terapias Complementares do DF (CRTCD-DF)'), ('CQBRA', 'Conselho de Quiropraxia de Brasília (CQBRA)'), ('CHDF', 'Conselho de Homeopatia do Distrito Federal (CHDF)'), ('CRMTCB-DF', 'Conselho Regional de Medicina Tradicional Chinesa em Brasília (CRMTCB-DF)'), ('CTH-DF', 'Conselho de Terapias Holísticas do DF (CTH-DF)'), ('CRTADF', 'Conselho Regional de Terapeutas Alternativos do Distrito Federal (CRTADF)')], default='CRAD-DF', max_length=10, verbose_name='Tipo de Conselho')),
            ],
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='crm',
        ),
        migrations.AddField(
            model_name='therapist',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.council', verbose_name='Conselho de Registro'),
        ),
    ]
