# Generated by Django 4.2.3 on 2023-10-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
