# Generated by Django 4.2.3 on 2023-10-04 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_rename_specialty_benefit_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Tratamento')),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('indigo', 'Indigo'), ('roxo', 'Roxo'), ('rosa', 'Rosa'), ('vermelho', 'Vermelho'), ('laranja', 'Laranja'), ('amarelo', 'Amarelo'), ('verde', 'Verde'), ('teal', 'Teal'), ('ciano', 'Ciano'), ('branco', 'Branco')], default='branco', max_length=15)),
            ],
            options={
                'verbose_name': 'Tipo de Tratamento',
                'verbose_name_plural': 'Tipos de Tratamento',
            },
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Tratamento'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='treatment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmenttype'),
        ),
    ]
