# Generated by Django 4.2.3 on 2023-09-28 04:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255, null=None, verbose_name='Nome conforme documento')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('birthday', models.DateField(verbose_name='Data de aniversário')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Celular')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('groups', models.ManyToManyField(blank=True, related_name='baseuser_groups', to='auth.group', verbose_name='Groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='baseuser_user_permissions', to='auth.permission', verbose_name='User Permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Segunda-feira'), ('Tuesday', 'Terça-feira'), ('Wednesday', 'Quarta-feira'), ('Thursday', 'Quinta-feira'), ('Friday', 'Sexta-feira'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=10, unique=True, verbose_name='Dia da Semana')),
            ],
            options={
                'verbose_name': 'Day of the Week',
                'verbose_name_plural': 'Days of the Week',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Speciality Name')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF com validação de dígitos')),
                ('rg_or_rne', models.CharField(max_length=20, null=None, unique=True, verbose_name='RG ou RNE com validação de dígitos')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('zip_code', models.CharField(max_length=100, verbose_name='CEP')),
                ('street_address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('accounts.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('RECEPTIONIST', 'Recepcionista'), ('MANAGER', 'Gerente'), ('GENERAL_MANAGER', 'Gerente Geral'), ('ADMINISTRATOR', 'Administrador'), ('SUPER_ADMIN', 'Super Admin')], max_length=15, verbose_name='Tipo de Usuário')),
            ],
            options={
                'verbose_name': 'Usuário do Sistema',
                'verbose_name_plural': 'Usuários do Sistema',
            },
            bases=('accounts.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crm', models.CharField(max_length=20, verbose_name='Cadastro do Órgão de Registro (ex: CRM)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa Administrativa (visível somente pelo gerente/administrador)')),
                ('photo', models.ImageField(upload_to='terapeutas/', verbose_name='Foto do Terapeuta')),
                ('contract_scan', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Anexo do Contrato com o Terapeuta')),
                ('availability_days', models.ManyToManyField(blank=True, default=None, to='accounts.dayofweek', verbose_name='Dias de Consulta')),
                ('availability_hours', models.ManyToManyField(blank=True, default=None, to='accounts.timeslot', verbose_name='Horários de Consulta')),
                ('specialities', models.ManyToManyField(to='accounts.speciality', verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
            },
            bases=('accounts.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
