# Generated by Django 4.2.3 on 2023-10-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
        ('appointments', '0002_alter_appointment_service'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialities',
            field=models.ManyToManyField(to='treatments.speciality', verbose_name='Especialidades'),
        ),
    ]
