# Generated by Django 4.2.3 on 2023-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_speciality_alter_therapist_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='jogo.jpeg', upload_to='clientes/', verbose_name='Foto do Cliente'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='photo',
            field=models.ImageField(default='jogo.jpeg', upload_to='usuarios/', verbose_name='Foto do Terapeuta'),
        ),
    ]
