# Generated by Django 4.2.2 on 2023-09-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date_start",
                    models.DateTimeField(
                        verbose_name="Data e Hora do início do Atendimento"
                    ),
                ),
                (
                    "appointment_date_end",
                    models.DateTimeField(
                        verbose_name="Data e Hora do término do Atendimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Cancelada"),
                            ("COMPLETED", "Concluída"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_appointments",
                        to="accounts.speciality",
                        verbose_name="Tipo de Tratamento",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_appointments",
                        to="accounts.therapist",
                        verbose_name="Terapeuta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendimento",
                "verbose_name_plural": "Atendimentos",
            },
        ),
        migrations.CreateModel(
            name="AppointmentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Pacote"),
                ),
                ("description", models.TextField(verbose_name="Observações")),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Original"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço com Desconto",
                    ),
                ),
                (
                    "appointments",
                    models.ManyToManyField(
                        to="appointments.appointment", verbose_name="Atendimentos"
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_packages",
                        to="accounts.therapist",
                        verbose_name="Terapeuta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Package",
                "verbose_name_plural": "Appointment Packages",
            },
        ),
    ]
