# Generated by Django 4.2.3 on 2023-10-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Data do Atendimento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='PENDING', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('appointment_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_appointments', to='accounts.timeslot', verbose_name='Horário do Atendimento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.client', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='treatments.speciality', verbose_name='Tipo de Tratamento')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to='accounts.therapist', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='AppointmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Pacote')),
                ('description', models.TextField(verbose_name='Observações')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Original')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço com Desconto')),
                ('appointments', models.ManyToManyField(to='appointments.appointment', verbose_name='Atendimentos')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_packages', to='accounts.therapist', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Appointment Package',
                'verbose_name_plural': 'Appointment Packages',
            },
        ),
    ]
