# Generated by Django 4.2.3 on 2023-10-11 00:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Sala')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_end',
            field=models.TimeField(default=datetime.time(8, 30), verbose_name='Hora de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Hora de Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_appointments', to='appointments.room', verbose_name='Sala'),
            preserve_default=False,
        ),
    ]
