# Generated by Django 4.2.3 on 2023-10-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Tratamento')),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('indigo', 'Indigo'), ('roxo', 'Roxo'), ('rosa', 'Rosa'), ('vermelho', 'Vermelho'), ('laranja', 'Laranja'), ('amarelo', 'Amarelo'), ('verde', 'Verde'), ('teal', 'Teal'), ('ciano', 'Ciano'), ('branco', 'Branco')], default='branco', max_length=15)),
            ],
            options={
                'verbose_name': 'Tipo de Tratamento',
                'verbose_name_plural': 'Tipos de Tratamento',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Tratamento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('feature_img', models.ImageField(upload_to='terapias/', verbose_name='Imagem de Destaque da Terapia')),
                ('treatment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmenttype')),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo Beneficio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.speciality')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
            },
        ),
    ]
