# Generated by Django 4.2.3 on 2023-10-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='Duração (em horas)'),
        ),
    ]
