name: Django CI

on:
  push:

env:
    SQL_ENGINE: django.db.backends.sqlite3
    SECRET_KEY: 094b1ce318f7283699d6d978bad7671d8419bf4a
    ACCESS_KEY: ${{ secrets.TEST_EC2_KEY }}
    SSH_USER: ${{ vars.HOMOLOG_SSH_USER }} 
    SSH_HOST: ${{ vars.HOMOLOG_SSH_HOST }}
    GIT_REPO_PATH: ${{ vars.HOMOLOG_GIT_REPO_PATH }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim-buster

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies and Sqlite3 Migrations
      run: |
        apt-get update && \
        apt-get install -y openssh-client
    
    - name: Deploy Changes to Homolog Env
      run: |
        ./deploy.sh