name: Django CI

on:
  push:

env:
    SQL_ENGINE: django.db.backends.sqlite3
    SECRET_KEY: 094b1ce318f7283699d6d978bad7671d8419bf4a

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim-buster

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies and Sqlite3 Migrations
      run: |
        apt-get update && \
        apt-get install -y libgirepository1.0-dev libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install poetry
        poetry install --with dev
        python manage.py makemigrations --noinput
        python manage.py migrate